from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from app.models.analysis import SkillStatus

class AnalysisCreateRequest(BaseModel):
    resume_id: int
    job_id: Optional[int] = None
    # Support custom job description comparison on the fly
    custom_job_title: Optional[str] = None
    custom_company: Optional[str] = None
    custom_job_description: Optional[str] = None
    custom_required_skills: Optional[List[str]] = None

class SkillGapOut(BaseModel):
    skill_name: str
    status: SkillStatus
    learning_recommendation: Optional[str] = None

    class Config:
        from_attributes = True

class AnalysisDetailOut(BaseModel):
    id: int
    resume_id: int
    job_id: int
    candidate_name: str
    candidate_email: str
    resume_filename: str
    job_title: str
    company: str
    experience_level: str
    similarity_score: float                # TF-IDF Cosine Similarity percentage (0-100)
    skill_match_percentage: float          # Required skills matched percentage (0-100)
    matched_skill_count: int
    required_skill_count: int
    matched_skills: List[str] = []
    missing_skills: List[str] = []
    additional_skills: List[str] = []
    learning_recommendations: List[Dict[str, str]] = []
    metric_disclaimer: str = "This Job Match Score is an automated text and skill similarity metric generated by the platform. It does not represent hiring probability or guarantee employment selection."
    created_at: datetime

    class Config:
        from_attributes = True

class AnalysisHistoryItem(BaseModel):
    id: int
    resume_id: int
    job_id: int
    resume_filename: str
    candidate_name: str
    job_title: str
    company: str
    similarity_score: float
    skill_match_percentage: float
    matched_skill_count: int
    required_skill_count: int
    created_at: datetime

    class Config:
        from_attributes = True

class CandidateComparisonItem(BaseModel):
    analysis_id: int
    candidate_id: int
    candidate_name: str
    candidate_email: str
    resume_id: int
    resume_filename: str
    similarity_score: float
    skill_match_percentage: float
    matched_skills: List[str]
    missing_skills: List[str]
    additional_skills: List[str]
    created_at: datetime

class CandidateStatsOut(BaseModel):
    total_resumes: int
    latest_resume: Optional[Dict[str, Any]] = None
    detected_skills_count: int
    total_analyses: int
    recent_analyses: List[AnalysisHistoryItem] = []

class RecruiterStatsOut(BaseModel):
    total_jobs: int
    total_resumes: int
    total_analyses: int
    avg_similarity_score: float
    job_analyses_distribution: List[Dict[str, Any]] = []
    top_demanded_skills: List[Dict[str, Any]] = []
    recent_analyses: List[AnalysisHistoryItem] = []
